[package]
name = "fighting_sisters"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
description = "A collection of static hero icons."

[dependencies]
maud = "0.26.0"
rocket = { version = "0.5.1"}
ureq = "2.12.1"

[workspace]
members = ["asset_server"]
